import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { formatEgp, propertyTypeLabels, suitabilityLabels } from "@/lib/marketplace";
import { trpc } from "@/lib/trpc";
import { CheckCircle2, CircleAlert, Eye, LoaderCircle, MapPin, Trash2, UsersRound, XCircle } from "lucide-react";
import { useState } from "react";
import { actionErrorMessages } from "@/lib/errorMessages";
import { showActionError, toast } from "@/lib/appToast";

type ReviewStatus = "VERIFIED" | "NEEDS_CHANGES" | "REJECTED";

const rejectionTemplates = [
  { label: "صور غير واضحة", reason: "يرجى رفع صور أوضح ومضيئة تُظهر تفاصيل العقار بشكل صحيح.", mediaQualityIssue: true },
  { label: "مراجعة العنوان الدقيق", reason: "يرجى مسح العنوان الدقيق أو رقم العمارة أو أرقام الهواتف من الوصف لحماية الخصوصية.", mediaQualityIssue: false },
  { label: "صور لا تمثل العقار", reason: "يرجى رفع صور حقيقية تمثل العقار المعروض وتفاصيله الفعلية.", mediaQualityIssue: true },
  { label: "استكمال تفاصيل الإعلان", reason: "يرجى استكمال تفاصيل العقار والتأكد من دقة المعلومات قبل إعادة الإرسال.", mediaQualityIssue: false },
] as const;

const stagedFieldLabels: Record<string, string> = { title: "العنوان", property_type: "نوع العقار", governorate: "المحافظة", city: "المدينة", area: "المنطقة", approximate_location: "الموقع التقريبي", description: "الوصف", monthly_price: "السعر الشهري", bedrooms: "الغرف", bathrooms: "الحمامات", capacity: "السعة", rent_type: "طريقة التأجير", total_beds: "إجمالي الأسرة", gender_suitability: "ملاءمة السكن", furnished: "التأثيث", amenities: "التجهيزات" };
const formatStagedValue = (value: unknown) => Array.isArray(value) ? value.join("، ") : value === true ? "نعم" : value === false ? "لا" : String(value ?? "—");

export function PropertyMediaReviewCard({ item, onReview, pending, isSuperAdmin = false, onDeleteProperty }: { item: any; onReview: (payload: any) => void; pending: boolean; isSuperAdmin?: boolean; onDeleteProperty?: (propertyId: string) => void }) {
  const [reason, setReason] = useState("");
  const [description, setDescription] = useState(item.description ?? "");
  const [mediaQualityIssue, setMediaQualityIssue] = useState(false);
  const [selectedPhoto, setSelectedPhoto] = useState<any | null>(null);
  const [previewOpen, setPreviewOpen] = useState(false);
  const [archiveOpen, setArchiveOpen] = useState(false);
  const [facts, setFacts] = useState({ ownerIdentityVerified: false, propertyVideoVerified: false, locationVerified: false, availabilityVerified: false, propertyPhotosQualityVerified: false });
  const stagedEdits = item.pendingEdits ?? {};
  const isStagedEdit = Boolean(item.hasPendingUpdates);
  const stagedFields = Object.entries(stagedEdits).filter(([key]) => !["exact_lat", "exact_lng", "street"].includes(key));
  const liveValues: Record<string, unknown> = { title: item.title, property_type: item.propertyType, governorate: item.governorate, city: item.city, area: item.area, approximate_location: item.approximateLocation, description: item.description, monthly_price: item.monthlyPrice, bedrooms: item.bedrooms, bathrooms: item.bathrooms, capacity: item.capacity, rent_type: item.rentType, total_beds: item.totalBeds, gender_suitability: item.genderSuitability, furnished: item.furnished, amenities: item.amenities };
  const updateDescription = trpc.admin.updatePropertyDescription.useMutation({ onSuccess: () => toast.success("تم حفظ الوصف المنقح قبل قرار المراجعة."), onError: error => showActionError(error, actionErrorMessages.moderation) });
  const archiveEligibility = trpc.superAdmin.propertyDeletionEligibility.useQuery({ propertyId: item.id }, { enabled: isSuperAdmin && archiveOpen, retry: false });
  const photos = (item.media ?? []).filter((media: any) => media.mediaType === "image").sort((left: any, right: any) => (left.sortOrder ?? 0) - (right.sortOrder ?? 0));
  const evidence = (item.media ?? []).filter((media: any) => media.mediaType === "verification_document");
  const canArchive = Boolean(archiveEligibility.data?.canArchive ?? archiveEligibility.data?.canDelete);

  const decide = (status: ReviewStatus) => {
    const mediaReason = status === "REJECTED" && mediaQualityIssue;
    if (status !== "VERIFIED" && !reason.trim()) return toast.error("سبب القرار مطلوب ليظهر للمالك.");
    if (mediaReason && reason.trim().length < 12) return toast.error("اكتب سبباً واضحاً لا يقل عن 12 حرفاً لرفض الصور.");
    onReview({ propertyId: item.id, status, reason: status === "VERIFIED" ? undefined : reason.trim(), mediaQualityIssue: mediaReason, ...facts });
  };

  const applyTemplate = (label: string) => {
    const template = rejectionTemplates.find(candidate => candidate.label === label);
    if (template) { setReason(template.reason); setMediaQualityIssue(template.mediaQualityIssue); }
  };

  return <article className="rounded-[24px] border border-[#e2e8ee] bg-white p-5 shadow-[0_8px_24px_rgba(16,42,67,.04)]">
    <header className="flex flex-col justify-between gap-4 lg:flex-row">
      <div><div className="flex flex-wrap items-center gap-2"><h3 className="text-lg font-black">{item.title}</h3><Badge className={`rounded-full border-0 px-2.5 py-1 text-[10px] font-bold ${isStagedEdit ? "bg-[#eff6ff] text-[#2563eb]" : "bg-[#fff5df] text-[#a96903]"}`}>{isStagedEdit ? "تعديلات مقترحة" : item.verificationStatus === "pending" ? "قيد المراجعة" : "يتطلب تعديلاً"}</Badge></div><p className="mt-2 flex items-center gap-1.5 text-sm text-[#6e8195]"><MapPin className="h-4 w-4 text-[#2563eb]" />{item.area}، {item.city} · {formatEgp(item.monthlyPrice)} جنيه</p><p className="mt-4 max-w-3xl text-sm leading-7 text-[#556d83]">{item.description}</p></div>
      <p className="max-w-sm rounded-lg bg-[#f8fafc] px-3 py-2 text-xs leading-5 text-[#62788d]">هذه مساحة مراجعة داخلية. يستخدم الطالب موقعاً عاماً مموهاً ولا يرى الإحداثيات الدقيقة أو الوصف الأصلي.</p>
    </header>

    {isStagedEdit ? <section className="mt-4 rounded-2xl border border-[#bfdbfe] bg-[#eff6ff] p-4"><h4 className="text-sm font-black text-[#0f172a]">مقارنة التعديلات المقترحة</h4><p className="mt-1 text-xs leading-5 text-[#475569]">القيمة المشطوبة هي المنشورة الآن؛ القيمة الخضراء هي المقترح الذي لن يظهر للطلاب إلا بعد اعتمادك.</p><dl className="mt-4 grid gap-3 sm:grid-cols-2">{stagedFields.map(([key, value]) => <div key={key} className="rounded-xl border border-[#dbeafe] bg-white p-3 text-sm"><dt className="font-black text-[#314b63]">{stagedFieldLabels[key] ?? key}</dt><dd className="mt-2 rounded-lg bg-[#fef2f2] px-2.5 py-2 text-xs leading-5 text-[#b91c1c] line-through"><span className="ml-1 font-black no-underline">الحالي:</span>{formatStagedValue(liveValues[key])}</dd><dd className="mt-2 rounded-lg bg-[#ecfdf5] px-2.5 py-2 text-sm font-bold leading-6 text-[#047857]"><span className="ml-1">المقترح:</span>{formatStagedValue(value)}</dd></div>)}</dl>{("exact_lat" in stagedEdits || "exact_lng" in stagedEdits) && <div className="mt-3 rounded-xl border border-[#dbeafe] bg-white p-3 text-xs"><b className="text-[#314b63]">الإحداثيات الدقيقة (داخلية فقط)</b><p className="mt-2 font-mono text-[#b91c1c] line-through">الحالية: {item.exactLat}, {item.exactLng}</p><p className="mt-1 font-mono font-bold text-[#047857]">المقترحة: {stagedEdits.exact_lat ?? item.exactLat}, {stagedEdits.exact_lng ?? item.exactLng}</p></div>}</section> : <section className="mt-4 rounded-2xl border border-[#e2e8ee] bg-[#f8fafc] p-4"><label className="text-sm font-black">تنقيح الوصف قبل الاعتماد</label><p className="mt-1 text-xs leading-5 text-[#62788d]">استخدم هذا الحقل لإزالة أي رقم مبنى أو رقم هاتف أو وصف يكشف العنوان الدقيق قبل النشر.</p><textarea value={description} onChange={event => setDescription(event.target.value)} className="mt-3 min-h-24 w-full rounded-xl border border-[#dbe4eb] bg-white p-3 text-sm leading-6 outline-none focus:border-[#2563eb]" /><div className="mt-3 flex justify-end"><Button type="button" variant="outline" disabled={updateDescription.isPending || description.trim().length < 20 || description.trim() === String(item.description ?? "").trim()} onClick={() => updateDescription.mutate({ propertyId: item.id, description: description.trim() })} className="h-9 rounded-xl text-xs font-bold">{updateDescription.isPending ? <><LoaderCircle className="ml-1.5 h-3.5 w-3.5 animate-spin" />جارٍ الحفظ...</> : "حفظ الوصف المنقح"}</Button></div></section>}

    <section className="mt-4 grid gap-3 rounded-2xl border border-[#e2e8ee] bg-[#f8fafc] p-4 md:grid-cols-2"><div><h4 className="text-sm font-black">الوصف الأصلي المقدم من المالك</h4><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-[#536b80]">{item.ownerDescription ?? item.description ?? "—"}</p></div><div><h4 className="text-sm font-black">إحداثيات المبنى الدقيقة — للمراجعة الداخلية</h4><p className="mt-2 font-mono text-xs leading-6 text-[#536b80]">{Number.isFinite(item.exactLat) && Number.isFinite(item.exactLng) ? `${item.exactLat}, ${item.exactLng}` : "لم يحدد المالك دبوساً دقيقاً بعد."}</p><p className="mt-2 text-xs leading-5 text-[#8c471d]">لا تُنشر هذه الإحداثيات أو هذا الوصف الأصلي للطلاب.</p></div></section>

    <section className="mt-5"><div className="flex flex-wrap items-center justify-between gap-2"><div><h4 className="font-black">صور العقار الخاصة للمراجعة</h4><p className="mt-1 text-xs text-[#62788d]">تظل الصور خاصة حتى قرار الاعتماد. النسخة العامة الحالية، إن وجدت، تحمل علامة Sakan 4U المائية.</p></div><span className={`rounded-full px-2.5 py-1 text-xs font-black ${photos.length >= 3 ? "bg-[#e7f6ef] text-[#059669]" : "bg-[#eff6ff] text-[#b91c1c]"}`}>{photos.length}/3 صور</span></div><div className="mt-3 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4">{photos.map((media: any, index: number) => <button type="button" key={media.id} onClick={() => setSelectedPhoto(media)} className="overflow-hidden rounded-xl border border-[#cbd5e1] bg-[#f8fafc] text-right transition hover:border-[#2563eb]"><img src={media.url} alt={media.description || `صورة العقار ${index + 1}`} className="aspect-[4/3] w-full object-cover" /><span className="block px-2 py-2 text-[10px] font-bold text-[#475569]">{media.isPrimary ? "صورة الغلاف" : `الصورة ${index + 1}`}{media.tag ? ` · ${media.tag}` : ""}<span className="mt-1 block">{media.watermarkStatus === "watermarked" ? "نسخة عامة جاهزة" : "مصدر خاص"}</span></span></button>)}</div>{evidence.length > 0 && <div className="mt-4 rounded-xl border border-[#c8d9e7] bg-[#edf5fa] p-3"><b className="text-sm text-[#0f172a]">إثبات الملكية (سري للإدارة فقط) — أدلة تحقق خاصة</b><p className="mt-1 text-xs leading-5 text-[#536b80]">هذه المستندات لا تُنشر للعامة؛ يفتحها Admin أو Super Admin فقط عبر رابط مؤقت وآمن للمراجعة الداخلية.</p><div className="mt-2 flex flex-wrap gap-2">{evidence.map((media: any) => media.url ? <a key={media.id} href={media.url} target="_blank" rel="noreferrer" className="rounded-lg bg-white px-3 py-2 text-xs font-bold text-[#2563eb] shadow-sm">فتح {media.originalName}</a> : null)}</div></div>}</section>

    <section className="mt-5 grid gap-3 rounded-2xl bg-[#f8fafc] p-4 md:grid-cols-2"><div><p className="text-sm font-black">تأكيدات المراجع</p><div className="mt-3 grid gap-2 text-sm font-bold text-[#536b80]"><label className="flex items-start gap-2 rounded-lg bg-white p-2.5"><input className="mt-1" type="checkbox" checked={facts.propertyPhotosQualityVerified} onChange={event => setFacts({ ...facts, propertyPhotosQualityVerified: event.target.checked })} />تم التحقق من أن الصور تمثل العقار الفعلي وبجودة مناسبة.</label>{[["ownerIdentityVerified", "هوية المالك"], ["propertyVideoVerified", "فيديو العقار"], ["locationVerified", "الموقع التقريبي"], ["availabilityVerified", "التوفر الحالي"]].map(([key, label]) => <label key={key} className="flex items-start gap-2"><input className="mt-1" type="checkbox" checked={facts[key as keyof typeof facts]} onChange={event => setFacts({ ...facts, [key]: event.target.checked })} />{label}</label>)}</div></div><div><label className="text-sm font-black">قالب سبب القرار</label><select defaultValue="" onChange={event => applyTemplate(event.target.value)} className="mt-2 h-10 w-full rounded-xl border border-[#dbe4eb] bg-white px-3 text-sm font-bold text-[#475569]"><option value="">اختر قالباً ثم عدّله</option>{rejectionTemplates.map(template => <option key={template.label} value={template.label}>{template.label}</option>)}</select><label className="mt-3 block text-sm font-black">سبب القرار الذي سيراه المالك</label><textarea value={reason} onChange={event => setReason(event.target.value)} className="mt-2 min-h-28 w-full rounded-xl border border-[#dbe4eb] bg-white p-3 text-sm outline-none focus:border-[#2563eb]" /><label className="mt-3 flex items-start gap-2 text-xs font-bold text-[#8c471d]"><input className="mt-0.5" type="checkbox" checked={mediaQualityIssue} onChange={event => setMediaQualityIssue(event.target.checked)} />سبب الرفض متعلق بجودة الصور أو ملاءمتها.</label></div></section>

    <div className="mt-4 flex flex-wrap gap-2"><Button type="button" onClick={() => setPreviewOpen(true)} variant="outline" className="h-10 rounded-xl border-[#d6e3ed] text-sm font-extrabold text-[#2563eb]"><Eye className="ml-2 h-4 w-4" />معاينة الطالب</Button><Button onClick={() => decide("VERIFIED")} disabled={pending || (!isStagedEdit && (photos.length < 3 || !facts.propertyPhotosQualityVerified))} className="h-10 rounded-xl bg-[#059669] text-sm font-extrabold hover:bg-[#12613f]"><CheckCircle2 className="ml-2 h-4 w-4" />{pending ? <><LoaderCircle className="ml-2 h-4 w-4 animate-spin" />جارٍ الحفظ...</> : isStagedEdit ? "اعتماد التعديلات" : "اعتماد"}</Button><Button onClick={() => decide("NEEDS_CHANGES")} disabled={pending || !reason.trim()} variant="outline" className="h-10 rounded-xl border-[#e8b46c] text-sm font-extrabold text-[#9d6201]"><CircleAlert className="ml-2 h-4 w-4" />{pending ? <><LoaderCircle className="ml-2 h-4 w-4 animate-spin" />جارٍ الحفظ...</> : isStagedEdit ? "رفض التعديلات" : "طلب تعديل"}</Button>{!isStagedEdit && <Button onClick={() => { setMediaQualityIssue(true); decide("REJECTED"); }} disabled={pending || reason.trim().length < 12} variant="outline" className="h-10 rounded-xl border-[#f0b8b0] text-sm font-extrabold text-[#b74a3b]"><XCircle className="ml-2 h-4 w-4" />{pending ? <><LoaderCircle className="ml-2 h-4 w-4 animate-spin" />جارٍ الحفظ...</> : "رفض بسبب الصور"}</Button>}{isSuperAdmin && <Button onClick={() => setArchiveOpen(true)} disabled={pending} variant="outline" className="h-10 rounded-xl border-[#f0b8b0] text-sm font-extrabold text-[#b91c1c]"><Trash2 className="ml-2 h-4 w-4" />{pending ? <><LoaderCircle className="ml-2 h-4 w-4 animate-spin" />جارٍ الحفظ...</> : "أرشفة آمنة"}</Button>}</div>

    <Dialog open={archiveOpen} onOpenChange={setArchiveOpen}><DialogContent dir="rtl" className="max-w-md rounded-[24px]"><DialogHeader><DialogTitle className="text-right">أرشفة عقار بإدارة المدير العام</DialogTitle></DialogHeader><div className="space-y-3 text-right"><p className="text-sm leading-6 text-[#61788d]">الأرشفة تخفي العقار من النتائج وطابور المراجعة وتحفظ الحجوزات والمراجعات والوسائط التاريخية.</p>{archiveEligibility.isLoading ? <p className="rounded-xl bg-[#f8fafc] p-3 text-xs text-[#64748b]">جارٍ التحقق من الأهلية...</p> : <p className={`rounded-xl p-3 text-xs font-bold leading-6 ${canArchive ? "bg-[#e7f6ef] text-[#059669]" : "bg-[#eff6ff] text-[#b91c1c]"}`}>{archiveEligibility.data?.message ?? "تعذر التحقق من أهلية الأرشفة."}</p>}<Button type="button" disabled={!canArchive || pending} onClick={() => { onDeleteProperty?.(item.id); setArchiveOpen(false); }} className="h-10 w-full rounded-xl bg-[#b91c1c] font-extrabold hover:bg-[#9f3f23]">{pending ? <><LoaderCircle className="ml-2 h-4 w-4 animate-spin" />جارٍ الحفظ...</> : "تأكيد الأرشفة الآمنة"}</Button></div></DialogContent></Dialog>
    <Dialog open={previewOpen} onOpenChange={setPreviewOpen}><DialogContent dir="rtl" className="max-h-[92vh] max-w-3xl overflow-y-auto rounded-[24px]"><DialogHeader><DialogTitle className="text-right">معاينة كما سيظهر للطالب</DialogTitle></DialogHeader><section className="overflow-hidden rounded-2xl border border-[#e2e8ee] bg-[#f8fafc]"><div className="grid gap-5 p-5 md:grid-cols-[1.1fr_.9fr]"><div><div className="grid grid-cols-2 gap-2">{photos.slice(0, 4).map((photo: any, index: number) => <img key={photo.id} src={photo.url} alt={photo.description || `صورة العقار ${index + 1}`} className="aspect-[4/3] w-full rounded-xl object-cover" />)}</div><p className="mt-3 rounded-xl bg-[#eff6ff] p-3 text-xs leading-6 text-[#a45a32]">هذه المعاينة تستخدم النص والبيانات العامة فقط. لا تعرض الإحداثيات الدقيقة أو الوصف الأصلي الخاص بالمالك.</p></div><div><div className="flex flex-wrap gap-2"><Badge variant="outline" className="rounded-full bg-white">{propertyTypeLabels[item.propertyType] ?? item.propertyType}</Badge><Badge variant="outline" className="rounded-full bg-white">{suitabilityLabels[item.genderSuitability as keyof typeof suitabilityLabels] ?? item.genderSuitability}</Badge></div><h3 className="mt-4 text-2xl font-black text-[#0f172a]">{item.title}</h3><p className="mt-2 flex items-center gap-1.5 text-sm font-bold text-[#475569]"><MapPin className="h-4 w-4 text-[#2563eb]" />{item.approximateLocation ?? item.area}، {item.city}</p><p className="mt-4 text-3xl font-black text-[#0f172a]">{formatEgp(item.monthlyPrice)} <span className="text-sm text-[#64748b]">جنيه شهرياً</span></p><p className="mt-5 whitespace-pre-wrap text-sm leading-7 text-[#475569]">{description}</p><div className="mt-5 grid grid-cols-3 gap-2 text-center text-xs font-bold text-[#475569]"><span className="rounded-xl bg-white p-3">{item.bedrooms} غرف</span><span className="rounded-xl bg-white p-3">{item.bathrooms} حمامات</span><span className="rounded-xl bg-white p-3"><UsersRound className="mx-auto mb-1 h-4 w-4 text-[#2563eb]" />{item.capacity} أفراد</span></div></div></div></section></DialogContent></Dialog>
    <Dialog open={Boolean(selectedPhoto)} onOpenChange={open => { if (!open) setSelectedPhoto(null); }}><DialogContent dir="rtl" className="max-w-4xl overflow-hidden rounded-[24px]"><DialogHeader><DialogTitle className="text-right">{selectedPhoto?.isPrimary ? "صورة الغلاف" : "معاينة صورة العقار"}</DialogTitle></DialogHeader>{selectedPhoto && <div className="space-y-3"><img src={selectedPhoto.url} alt={selectedPhoto.description || "معاينة موسعة لصورة العقار"} className="max-h-[70vh] w-full rounded-xl bg-[#f8fafc] object-contain" /><div className="grid gap-2 text-sm text-[#536b80] sm:grid-cols-3"><p><b>الترتيب:</b> {(selectedPhoto.sortOrder ?? 0) + 1}</p><p><b>الوسم:</b> {selectedPhoto.tag || "—"}</p><p><b>الحالة:</b> {selectedPhoto.watermarkStatus === "watermarked" ? "مشتق عام جاهز" : "مصدر خاص"}</p></div>{selectedPhoto.description && <p className="rounded-xl bg-[#f8fafc] p-3 text-sm leading-6 text-[#536b80]">{selectedPhoto.description}</p>}</div>}</DialogContent></Dialog>
  </article>;
}
