import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { CalendarClock, CircleAlert, History, LoaderCircle, RotateCcw, XCircle } from "lucide-react";
import { useState } from "react";
import { actionErrorMessages } from "@/lib/errorMessages";
import { showActionError, toast } from "@/lib/appToast";

const localDateTime = (date?: string) => {
  const value = date ? new Date(date) : new Date(Date.now() + 86_400_000);
  return new Date(value.getTime() - value.getTimezoneOffset() * 60_000).toISOString().slice(0, 16);
};

const eventLabels: Record<string, string> = {
  reschedule_requested: "طلب تغيير موعد", reschedule_confirmed: "اعتماد/تعديل موعد", cancellation_requested: "طلب إلغاء", cancellation_confirmed: "تأكيد الإلغاء", no_show_recorded: "تسجيل عدم حضور", refund_review_opened: "فتح مراجعة استرداد", refund_approved: "اعتماد استرداد", refund_declined: "رفض استرداد",
};

export function StaffAppointmentExceptionPanel({ item, onChanged }: { item: any; onChanged: () => void }) {
  const [confirmedAt, setConfirmedAt] = useState(localDateTime(item.rescheduleRequest?.requestedViewingAt ?? item.viewingScheduledAt));
  const [staffAt, setStaffAt] = useState(localDateTime(item.viewingScheduledAt));
  const [reason, setReason] = useState("");
  const [noShowParty, setNoShowParty] = useState<"student" | "owner" | "both">("student");
  const [refundDecision, setRefundDecision] = useState<"approved" | "declined">("declined");
  const [refundAmount, setRefundAmount] = useState("");
  const [refundReference, setRefundReference] = useState("");
  const done = (message: string) => { toast.success(message); onChanged(); setReason(""); };
  const reschedule = trpc.bookings.confirmReschedule.useMutation({ onSuccess: () => done("تم اعتماد الموعد الجديد."), onError: error => showActionError(error, actionErrorMessages.bookingDecision) });
  const staffReschedule = trpc.bookings.staffReschedule.useMutation({ onSuccess: () => done("تم تعديل الموعد وتسجيله في السجل التشغيلي."), onError: error => showActionError(error, actionErrorMessages.bookingDecision) });
  const cancellation = trpc.bookings.confirmCancellation.useMutation({ onSuccess: () => done("تم اعتماد الإلغاء وفتح المراجعة اليدوية عند الحاجة."), onError: error => showActionError(error, actionErrorMessages.bookingDecision) });
  const staffCancel = trpc.bookings.staffCancel.useMutation({ onSuccess: () => done("تم تسجيل الإلغاء المسبب."), onError: error => showActionError(error, actionErrorMessages.bookingDecision) });
  const noShow = trpc.bookings.recordNoShow.useMutation({ onSuccess: () => done("تم تسجيل حالة عدم الحضور."), onError: error => showActionError(error, actionErrorMessages.bookingDecision) });
  const refund = trpc.bookings.recordRefundDecision.useMutation({ onSuccess: () => done("تم تسجيل القرار المالي اليدوي."), onError: error => showActionError(error, actionErrorMessages.bookingDecision) });
  const pending = reschedule.isPending || staffReschedule.isPending || cancellation.isPending || staffCancel.isPending || noShow.isPending || refund.isPending;
  const canOperate = item.status === "owner_confirmed" && item.paymentStatus === "paid" && !item.viewingCompletedAt;
  const noShowEligible = canOperate && item.viewingScheduledAt && new Date(item.viewingScheduledAt) <= new Date();
  const canCancel = ["pending", "contacted", "owner_confirmed"].includes(item.status) && !item.viewingCompletedAt;
  const refundPending = item.refundReviewStatus === "pending";
  const submitRefund = () => refund.mutate({ bookingId: item.id, decision: refundDecision, amount: refundDecision === "approved" ? Number(refundAmount) : null, reason: reason.trim(), reference: refundReference.trim() || undefined });

  return <section className="mt-4 rounded-2xl border border-[#cbd5e1] bg-[#fbfcfe] p-4"><div className="flex flex-wrap items-center gap-2"><CalendarClock className="h-4 w-4 text-[#2563eb]" /><b className="text-sm">إدارة استثناءات الموعد</b>{item.rescheduleRequest?.status === "pending" && <Badge className="border-0 bg-[#eaf0fb] text-[#2563eb]">طلب تغيير معلق</Badge>}{item.cancellationRequest?.status === "pending" && <Badge className="border-0 bg-[#eff6ff] text-[#b91c1c]">طلب إلغاء معلق</Badge>}{refundPending && <Badge className="border-0 bg-[#fff5df] text-[#a96903]">مراجعة استرداد يدوية</Badge>}</div>
    <p className="mt-2 text-xs leading-5 text-[#62788d]">كل إجراء أدناه يُسجل بسجل تشغيلي غير قابل للتعديل. لا يُنشئ أي إجراء عملية دفع أو استرداداً تلقائياً.</p>
    {item.rescheduleRequest?.status === "pending" && <div className="mt-3 rounded-xl bg-white p-3"><p className="text-xs leading-6 text-[#536b80]">طلب {item.rescheduleRequest.requestedByRole === "owner" ? "المالك" : "الطالب"}: {item.rescheduleRequest.reason}</p><div className="mt-3 flex flex-wrap gap-2"><Input value={confirmedAt} onChange={event => setConfirmedAt(event.target.value)} type="datetime-local" className="h-9 w-auto text-xs" /><Button disabled={pending || !confirmedAt} onClick={() => reschedule.mutate({ requestId: item.rescheduleRequest.id, viewingAt: new Date(confirmedAt).toISOString() })} className="h-9 rounded-lg bg-[#2563eb] text-xs font-extrabold hover:bg-[#274d80]">{pending ? <><LoaderCircle className="ml-1 h-3.5 w-3.5 animate-spin" />جارٍ الحفظ...</> : "اعتماد الموعد"}</Button></div></div>}
    {item.cancellationRequest?.status === "pending" && <div className="mt-3 rounded-xl bg-white p-3"><p className="text-xs leading-6 text-[#536b80]">سبب طلب الإلغاء: {item.cancellationRequest.reason}</p><Button disabled={pending} onClick={() => cancellation.mutate({ requestId: item.cancellationRequest.id })} className="mt-3 h-9 rounded-lg bg-[#b91c1c] text-xs font-extrabold hover:bg-[#9f4121]">{pending ? <><LoaderCircle className="ml-1 h-3.5 w-3.5 animate-spin" />جارٍ الحفظ...</> : "تأكيد الإلغاء"}</Button></div>}
    <div className="mt-3 grid gap-3 rounded-xl bg-white p-3 lg:grid-cols-2"><div><b className="text-xs">تعديل إداري مباشر للموعد</b><div className="mt-2 flex flex-wrap gap-2"><Input value={staffAt} onChange={event => setStaffAt(event.target.value)} type="datetime-local" className="h-9 w-auto text-xs" /><Button disabled={pending || !canOperate || !reason.trim() || !staffAt} onClick={() => staffReschedule.mutate({ bookingId: item.id, viewingAt: new Date(staffAt).toISOString(), reason: reason.trim() })} variant="outline" className="h-9 border-[#b8c8e2] text-xs font-bold text-[#2563eb]"><RotateCcw className="ml-1 h-3.5 w-3.5" />تعديل الموعد</Button></div></div><div><b className="text-xs">إلغاء إداري مباشر</b><div className="mt-2"><Button disabled={pending || !canCancel || !reason.trim()} onClick={() => staffCancel.mutate({ bookingId: item.id, reason: reason.trim() })} variant="outline" className="h-9 border-[#e8b9b4] text-xs font-bold text-[#b91c1c]"><XCircle className="ml-1 h-3.5 w-3.5" />تسجيل إلغاء</Button></div></div><label className="lg:col-span-2 text-xs font-bold">سبب الإجراء الإداري<Textarea value={reason} onChange={event => setReason(event.target.value)} placeholder="السبب مطلوب لكل إجراء مباشر أو مالي..." className="mt-2 min-h-20 text-xs" /></label></div>
    <div className="mt-3 grid gap-3 rounded-xl bg-white p-3 lg:grid-cols-2"><div><b className="text-xs">تسجيل عدم حضور</b><div className="mt-2 flex flex-wrap gap-2"><select value={noShowParty} onChange={event => setNoShowParty(event.target.value as typeof noShowParty)} className="h-9 rounded-lg border border-[#dce4eb] bg-white px-2 text-xs"><option value="student">الطالب</option><option value="owner">المالك</option><option value="both">الطرفان</option></select><Button disabled={pending || !noShowEligible || !reason.trim()} onClick={() => noShow.mutate({ bookingId: item.id, party: noShowParty, reason: reason.trim() })} variant="outline" className="h-9 border-[#e8b46c] text-xs font-bold text-[#9d6201]"><CircleAlert className="ml-1 h-3.5 w-3.5" />تسجيل عدم حضور</Button></div></div>{refundPending && <div><b className="text-xs">قرار الاسترداد اليدوي</b><div className="mt-2 flex flex-wrap gap-2"><select value={refundDecision} onChange={event => setRefundDecision(event.target.value as typeof refundDecision)} className="h-9 rounded-lg border border-[#dce4eb] bg-white px-2 text-xs"><option value="declined">لا يعتمد استرداد</option><option value="approved">اعتماد استرداد</option></select>{refundDecision === "approved" && <Input value={refundAmount} onChange={event => setRefundAmount(event.target.value)} type="number" min="1" placeholder="المبلغ" className="h-9 w-24 text-xs" />}<Input value={refundReference} onChange={event => setRefundReference(event.target.value)} placeholder="مرجع اختياري" className="h-9 w-28 text-xs" /><Button disabled={pending || !reason.trim() || (refundDecision === "approved" && Number(refundAmount) <= 0)} onClick={submitRefund} className="h-9 bg-[#059669] text-xs font-extrabold hover:bg-[#12613f]">{pending ? <><LoaderCircle className="ml-1 h-3.5 w-3.5 animate-spin" />جارٍ الحفظ...</> : "حفظ القرار"}</Button></div></div>}</div>
    <details className="mt-3 rounded-xl bg-white p-3"><summary className="flex cursor-pointer items-center gap-2 text-xs font-extrabold text-[#1e3a8a]"><History className="h-4 w-4" />السجل التشغيلي للمواعيد والقرارات</summary><div className="mt-3 space-y-2">{item.history?.length ? item.history.map((entry: any, index: number) => <div key={`${entry.createdAt}-${index}`} className="rounded-lg bg-[#f8fafc] p-2 text-xs leading-5 text-[#596f83]"><b className="text-[#0f172a]">{eventLabels[entry.eventType] ?? entry.eventType}</b> · {entry.actorRole ?? "نظام"}<br />{entry.previousViewingAt && <>من {new Date(entry.previousViewingAt).toLocaleString("ar-EG")} </>}{entry.newViewingAt && <>إلى {new Date(entry.newViewingAt).toLocaleString("ar-EG")} </>}{entry.reason && <><br />السبب: {entry.reason}</>}<br /><span className="text-[#8a99a8]">{new Date(entry.createdAt).toLocaleString("ar-EG")}</span></div>) : <p className="text-xs text-[#64748b]">لا توجد استثناءات مسجلة.</p>}</div></details>
  </section>;
}
