begin;

create or replace function private.enforce_booking_transition()
returns trigger language plpgsql security definer set search_path = '' as $$
declare actor_role public.app_role; operation text := coalesce(current_setting('app.sakeno_booking_operation', true), '');
begin
  if tg_op = 'INSERT' then
    if operation <> 'create_viewing_request' or auth.uid() is null or private.current_user_role() is distinct from 'student'::public.app_role or new.student_id is distinct from auth.uid() or new.status is distinct from 'pending'::public.booking_status or new.payment_status is distinct from 'pending'::public.viewing_payment_status or new.fee_amount is null or new.requested_viewing_at < now() then raise exception 'Only the authenticated student may create a pending viewing request' using errcode = '42501'; end if;
    return new;
  end if;
  if old.id is distinct from new.id or old.property_id is distinct from new.property_id or old.student_id is distinct from new.student_id or old.contact_name is distinct from new.contact_name or old.phone is distinct from new.phone or old.people_count is distinct from new.people_count or old.preferred_contact_time is distinct from new.preferred_contact_time or old.notes is distinct from new.notes or old.requested_viewing_at is distinct from new.requested_viewing_at or old.fee_amount is distinct from new.fee_amount or old.created_at is distinct from new.created_at then raise exception 'Viewing request details are immutable after creation' using errcode = '42501'; end if;
  actor_role := private.current_user_role();
  if operation = 'provider_payment' then
    if coalesce(current_setting('request.jwt.claim.role', true), '') <> 'service_role' or old.payment_status <> 'pending'::public.viewing_payment_status or new.payment_status <> 'paid'::public.viewing_payment_status or new.paid_at is null or new.payment_recorded_by is not null or old.status is distinct from new.status or old.viewing_scheduled_at is distinct from new.viewing_scheduled_at or old.viewing_completed_at is distinct from new.viewing_completed_at or old.student_viewing_decision is distinct from new.student_viewing_decision or old.fee_credit_status is distinct from new.fee_credit_status or old.fee_credited_at is distinct from new.fee_credited_at then raise exception 'Only a trusted provider adapter may confirm a matching payment' using errcode = '42501'; end if;
    return new;
  end if;
  if operation = 'record_payment' then
    if actor_role not in ('admin'::public.app_role, 'super_admin'::public.app_role) or old.payment_status <> 'pending'::public.viewing_payment_status or new.payment_status <> 'paid'::public.viewing_payment_status or new.paid_at is null or new.payment_recorded_by is distinct from auth.uid() or old.status is distinct from new.status or old.viewing_scheduled_at is distinct from new.viewing_scheduled_at or old.viewing_completed_at is distinct from new.viewing_completed_at or old.student_viewing_decision is distinct from new.student_viewing_decision or old.fee_credit_status is distinct from new.fee_credit_status or old.fee_credited_at is distinct from new.fee_credited_at then raise exception 'Only staff may record a verified viewing-fee payment' using errcode = '42501'; end if; return new;
  end if;
  if operation = 'schedule_viewing' then
    if actor_role not in ('admin'::public.app_role, 'super_admin'::public.app_role) or old.payment_status <> 'paid'::public.viewing_payment_status or old.status <> 'owner_confirmed'::public.booking_status or old.viewing_scheduled_at is not null or new.viewing_scheduled_at is null or new.viewing_scheduled_by is distinct from auth.uid() or old.status is distinct from new.status or old.payment_status is distinct from new.payment_status or old.viewing_completed_at is distinct from new.viewing_completed_at or old.student_viewing_decision is distinct from new.student_viewing_decision or old.fee_credit_status is distinct from new.fee_credit_status or old.fee_credited_at is distinct from new.fee_credited_at then raise exception 'Only staff may schedule a paid owner-confirmed viewing' using errcode = '42501'; end if; return new;
  end if;
  if operation = 'reschedule_viewing' then
    if actor_role not in ('admin'::public.app_role, 'super_admin'::public.app_role) or old.payment_status <> 'paid'::public.viewing_payment_status or old.status <> 'owner_confirmed'::public.booking_status or old.viewing_scheduled_at is null or old.viewing_completed_at is not null or new.viewing_scheduled_at is null or new.viewing_scheduled_at <= now() or new.viewing_scheduled_by is distinct from auth.uid() or old.status is distinct from new.status or old.payment_status is distinct from new.payment_status or old.viewing_completed_at is distinct from new.viewing_completed_at or old.student_viewing_decision is distinct from new.student_viewing_decision or old.fee_credit_status is distinct from new.fee_credit_status or old.fee_credited_at is distinct from new.fee_credited_at then raise exception 'Only staff may reschedule an incomplete paid viewing' using errcode = '42501'; end if; return new;
  end if;
  if operation = 'cancel_viewing' then
    if actor_role not in ('admin'::public.app_role, 'super_admin'::public.app_role) or old.status not in ('pending'::public.booking_status, 'contacted'::public.booking_status, 'owner_confirmed'::public.booking_status) or old.viewing_completed_at is not null or new.status <> 'cancelled'::public.booking_status or old.payment_status is distinct from new.payment_status or old.viewing_scheduled_at is distinct from new.viewing_scheduled_at or old.viewing_completed_at is distinct from new.viewing_completed_at or old.student_viewing_decision is distinct from new.student_viewing_decision or old.fee_credit_status is distinct from new.fee_credit_status or old.fee_credited_at is distinct from new.fee_credited_at then raise exception 'Only staff may confirm a reasoned pre-completion cancellation' using errcode = '42501'; end if; return new;
  end if;
  if operation = 'record_no_show' then
    if actor_role not in ('admin'::public.app_role, 'super_admin'::public.app_role) or old.status <> 'owner_confirmed'::public.booking_status or old.payment_status <> 'paid'::public.viewing_payment_status or old.viewing_scheduled_at is null or old.viewing_scheduled_at > now() or old.viewing_completed_at is not null or new.status <> 'no_show'::public.booking_status or old.payment_status is distinct from new.payment_status or old.viewing_scheduled_at is distinct from new.viewing_scheduled_at or old.viewing_completed_at is distinct from new.viewing_completed_at or old.student_viewing_decision is distinct from new.student_viewing_decision or old.fee_credit_status is distinct from new.fee_credit_status or old.fee_credited_at is distinct from new.fee_credited_at then raise exception 'Only staff may record a missed scheduled viewing' using errcode = '42501'; end if; return new;
  end if;
  if operation = 'complete_viewing' then
    if actor_role not in ('admin'::public.app_role, 'super_admin'::public.app_role) or old.payment_status <> 'paid'::public.viewing_payment_status or old.viewing_scheduled_at is null or old.viewing_completed_at is not null or new.viewing_completed_at is null or new.viewing_completed_by is distinct from auth.uid() or old.status is distinct from new.status or old.payment_status is distinct from new.payment_status or old.student_viewing_decision is distinct from new.student_viewing_decision or old.fee_credit_status is distinct from new.fee_credit_status or old.fee_credited_at is distinct from new.fee_credited_at then raise exception 'Only staff may complete a scheduled viewing' using errcode = '42501'; end if; return new;
  end if;
  if operation = 'student_decision' then
    if actor_role <> 'student'::public.app_role or old.student_id <> auth.uid() or old.payment_status <> 'paid'::public.viewing_payment_status or old.status <> 'owner_confirmed'::public.booking_status or old.viewing_completed_at is null or old.student_viewing_decision <> 'pending'::public.student_viewing_decision or not ((new.student_viewing_decision = 'accepted'::public.student_viewing_decision and new.status = 'student_confirmed'::public.booking_status and new.fee_credit_status = 'credited'::public.viewing_fee_credit_status and new.fee_credited_at is not null) or (new.student_viewing_decision = 'rejected'::public.student_viewing_decision and new.status = 'cancelled'::public.booking_status and new.fee_credit_status = 'not_credited'::public.viewing_fee_credit_status and new.fee_credited_at is null)) then raise exception 'The student viewing decision is not allowed for this request' using errcode = '42501'; end if; return new;
  end if;
  if operation <> 'transition' then raise exception 'Booking updates must use an authorized workflow operation' using errcode = '42501'; end if;
  if old.payment_status is distinct from new.payment_status or old.paid_at is distinct from new.paid_at or old.payment_recorded_by is distinct from new.payment_recorded_by or old.viewing_scheduled_at is distinct from new.viewing_scheduled_at or old.viewing_scheduled_by is distinct from new.viewing_scheduled_by or old.viewing_completed_at is distinct from new.viewing_completed_at or old.viewing_completed_by is distinct from new.viewing_completed_by or old.student_viewing_decision is distinct from new.student_viewing_decision or old.fee_credit_status is distinct from new.fee_credit_status or old.fee_credited_at is distinct from new.fee_credited_at then raise exception 'Payment and viewing fields require an authorized workflow operation' using errcode = '42501'; end if;
  if old.status is not distinct from new.status then return new; end if;
  if auth.uid() is null then raise exception 'Authentication is required to transition a booking' using errcode = '42501'; end if;
  if actor_role = 'owner'::public.app_role and private.owns_property(old.property_id) and ((old.status = 'pending'::public.booking_status and new.status in ('contacted'::public.booking_status, 'rejected'::public.booking_status)) or (old.status = 'contacted'::public.booking_status and new.status in ('owner_confirmed'::public.booking_status, 'rejected'::public.booking_status))) then return new; end if;
  if actor_role in ('admin'::public.app_role, 'super_admin'::public.app_role) and old.status = 'student_confirmed'::public.booking_status and new.status = 'completed'::public.booking_status then return new; end if;
  raise exception 'Booking status transition from % to % is not allowed for this role', old.status, new.status using errcode = '42501';
end;
$$;

commit;
